name: Deploy Keycloak Theme

on:
  push:
    branches: ["main"]
    paths:
      - "keycloak-theme/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Remove existing keycloak-theme folder on VPS
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo rm -rf /opt/keycloak/themes/fastsms/*
            sudo chown -R ${{ secrets.VPS_USER }}:${{ secrets.VPS_USER }} /opt/keycloak/themes/fastsms

      - name: Upload keycloak-theme folder to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "keycloak-theme/fastsms/*"
          target: "/home/${{ secrets.VPS_USER }}/fastsms-temp/"

      - name: Move uploaded theme folder to Keycloak themes directory
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mv /home/${{ secrets.VPS_USER }}/fastsms-temp/keycloak-theme/fastsms/* /opt/keycloak/themes/fastsms/
            sudo rm -rf /home/${{ secrets.VPS_USER }}/fastsms-temp

      - name: Set ownership of uploaded theme folder to keycloak user
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo chown -R keycloak:keycloak /opt/keycloak/themes/fastsms

      - name: Restart Keycloak
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl stop keycloak
            sudo systemctl start keycloak